#!/usr/bin/env bash
# script displays information about subdomains.

display_subdomain ()
{
	domain="$1"
	subdomain="$2"
	dig "$domain.$subdomain" | awk '/ANSWER SECTION:/{getline; printf "The subdomain %s is a %s record and points to %s\n", var, $4, $5}' var="$subdomain"
}

for subdomain in "www" "lb-01" "web-01" "web-02"
do
	if [ -z "$2" ] || [ "$2" == "$subdomain" ]
	then
	display_subdomain "$1" "$subdomain"
	fi
done
