#!/usr/bin/env bash
# installs nginx and configures it on a remote server

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo chmod -R 755 /var/www/thenabverse.tech/html
echo 'Hello World!' > /var/www/thenabverse.tech/html/index.html
service nginx start
