#!/usr/bin/env bash
# configures an Nginx server so that /redirect_me is redirecting to another page

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sed -i "46 a \t location {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n\t}" /etc/nginx/sites-available/default
sudo service nginx start
