#!/usr/bin/env bash
# Configures a new Ubuntu server with a custom HTTP header response
# shellcheck disable=SC2154
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo chmod -R 755 /var/www/html
echo 'Hello World!' | sudo tee /var/www/html/index.html
sudo sed -i "/server_name _;/a \\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
sudo sed -i "/http {/a\\\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
sudo sed -i "/server_name _;/a\\\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default
sudo service nginx start
sudo service nginx reload
