#!/usr/bin/env bash
# Configures a new Ubuntu server with a HAproxy load-balancer
sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.6
sudo apt-get -y update
sudo apt-get -y install haproxy=2.6.\*
sudo sed -i "$ a\frontend thenabverse\n\tbind *:80\n\tmode http\n\tdefault_backend web-servers\n\nbackend web-servers\n\tbalance roundrobin\n\tmode http\n\toption httpclose\n\toption forwardfor\n\tserver 24789-web-01 3.218.67.248:80 check\n\tserver 24789-web-02 3.236.227.91:80 check" /etc/haproxy/haproxy.cfg
sudo sed -i '/#EXTRAOPTS="-de -m 16"/a ENABLED=1' /etc/default/haproxy
sudo service haproxy start
